[tool.pytest.ini_options]
addopts = "-p requests_mock -sv" # Always load the 'requests_mock' plugin and run in verbose mode
markers = [
    "smoke : light-weight subset",
    "auth  : authentication tests"
]

[tool.black]
line-length = 120

[tool.isort]
line_length = 120

[tool.flake8]
max-line-length = 120
max-complexity = 6